"""One definition per report drives the HTML table, and the Excel export
identically — adding a new report means one entry here plus one function
in reports_service.py, not a bespoke route/template pair.
"""
from app.services import reports_service

REPORTS = {
    "action-status": {
        "title": "Action Status Report",
        "description": "Every task in the system, grouped by current status.",
        "icon": "bi-bar-chart",
        "compute": reports_service.action_status_report,
        "columns": [
            {"key": "status", "label": "Status", "type": "status"},
            {"key": "count", "label": "Count", "type": "number"},
            {"key": "percent", "label": "% of Total", "type": "percent"},
        ],
    },
    "employee-pending": {
        "title": "Employee-wise Pending Actions",
        "description": "Open, in-progress, on-hold and overdue counts per employee.",
        "icon": "bi-people",
        "compute": reports_service.employee_pending_report,
        "columns": [
            {"key": "name", "label": "Employee", "type": "text"},
            {"key": "department", "label": "Department", "type": "text"},
            {"key": "open", "label": "Open", "type": "number"},
            {"key": "in_progress", "label": "In Progress", "type": "number"},
            {"key": "on_hold", "label": "On Hold", "type": "number"},
            {"key": "overdue", "label": "Overdue", "type": "number"},
            {"key": "total_pending", "label": "Total Pending", "type": "number"},
        ],
    },
    "overdue": {
        "title": "Overdue Actions",
        "description": "Every open task past its due date, oldest due date first.",
        "icon": "bi-exclamation-triangle",
        "compute": reports_service.overdue_actions_report,
        "columns": [
            {"key": "title", "label": "Action", "type": "text"},
            {"key": "source", "label": "Source", "type": "text"},
            {"key": "assignees", "label": "Assigned To", "type": "text"},
            {"key": "priority", "label": "Priority", "type": "priority"},
            {"key": "due_date", "label": "Due Date", "type": "date"},
            {"key": "days_overdue", "label": "Days Overdue", "type": "number"},
        ],
    },
    "meeting-actions": {
        "title": "Meeting-wise Actions",
        "description": "Action item breakdown for every meeting that has at least one.",
        "icon": "bi-calendar3",
        "compute": reports_service.meeting_actions_report,
        "columns": [
            {"key": "meeting", "label": "Meeting", "type": "text"},
            {"key": "date", "label": "Date", "type": "date"},
            {"key": "total_actions", "label": "Total", "type": "number"},
            {"key": "open", "label": "Open", "type": "number"},
            {"key": "in_progress", "label": "In Progress", "type": "number"},
            {"key": "completed", "label": "Completed", "type": "number"},
            {"key": "overdue", "label": "Overdue", "type": "number"},
            {"key": "followup_status", "label": "Follow-up", "type": "text"},
        ],
    },
    "project-actions": {
        "title": "Project-wise Actions",
        "description": "Task breakdown for every project.",
        "icon": "bi-kanban",
        "compute": reports_service.project_actions_report,
        "columns": [
            {"key": "code", "label": "Code", "type": "text"},
            {"key": "project", "label": "Project", "type": "text"},
            {"key": "total_tasks", "label": "Total", "type": "number"},
            {"key": "open", "label": "Open", "type": "number"},
            {"key": "in_progress", "label": "In Progress", "type": "number"},
            {"key": "completed", "label": "Completed", "type": "number"},
            {"key": "overdue", "label": "Overdue", "type": "number"},
            {"key": "progress_percent", "label": "Progress", "type": "percent"},
        ],
    },
    "completed": {
        "title": "Completed Actions",
        "description": "Every completed task, most recent first, with time-to-close.",
        "icon": "bi-check-circle",
        "compute": reports_service.completed_actions_report,
        "columns": [
            {"key": "title", "label": "Action", "type": "text"},
            {"key": "source", "label": "Source", "type": "text"},
            {"key": "assignees", "label": "Assigned To", "type": "text"},
            {"key": "completed_date", "label": "Completed", "type": "date"},
            {"key": "days_to_complete", "label": "Days to Close", "type": "number"},
        ],
    },
    "ageing": {
        "title": "Ageing Analysis",
        "description": "How long open tasks have been sitting, bucketed by age.",
        "icon": "bi-hourglass-split",
        "compute": reports_service.ageing_report,
        "columns": [
            {"key": "title", "label": "Action", "type": "text"},
            {"key": "source", "label": "Source", "type": "text"},
            {"key": "assignees", "label": "Assigned To", "type": "text"},
            {"key": "priority", "label": "Priority", "type": "priority"},
            {"key": "status", "label": "Status", "type": "status"},
            {"key": "age_days", "label": "Age (days)", "type": "number"},
        ],
        "summary_is_buckets": True,
    },
    "completion-rate": {
        "title": "Employee Completion Rate",
        "description": "Completion rate, on-time rate, and average days to close, per employee.",
        "icon": "bi-graph-up",
        "compute": reports_service.employee_completion_rate_report,
        "columns": [
            {"key": "name", "label": "Employee", "type": "text"},
            {"key": "department", "label": "Department", "type": "text"},
            {"key": "total_assigned", "label": "Assigned", "type": "number"},
            {"key": "completed", "label": "Completed", "type": "number"},
            {"key": "completion_rate", "label": "Completion Rate", "type": "percent"},
            {"key": "on_time_rate", "label": "On-Time Rate", "type": "percent"},
            {"key": "avg_days_to_complete", "label": "Avg Days to Close", "type": "number"},
        ],
    },
    "project-progress": {
        "title": "Project Progress",
        "description": "Status, priority, health and progress for every project.",
        "icon": "bi-speedometer2",
        "compute": reports_service.project_progress_report,
        "columns": [
            {"key": "code", "label": "Code", "type": "text"},
            {"key": "project", "label": "Project", "type": "text"},
            {"key": "owner", "label": "Owner", "type": "text"},
            {"key": "status", "label": "Status", "type": "status"},
            {"key": "priority", "label": "Priority", "type": "priority"},
            {"key": "progress_percent", "label": "Progress", "type": "percent"},
            {"key": "health", "label": "Health", "type": "health"},
            {"key": "target_date", "label": "Target Date", "type": "date"},
        ],
    },
    "meeting-compliance": {
        "title": "Meeting Follow-up Compliance",
        "description": "Whether each completed meeting's actions were fully wrapped up.",
        "icon": "bi-calendar-check",
        "compute": reports_service.meeting_compliance_report,
        "columns": [
            {"key": "meeting", "label": "Meeting", "type": "text"},
            {"key": "date", "label": "Date", "type": "date"},
            {"key": "total_actions", "label": "Total Actions", "type": "number"},
            {"key": "completed_actions", "label": "Completed", "type": "number"},
            {"key": "followup_status", "label": "Follow-up Status", "type": "text"},
            {"key": "compliant", "label": "Compliant", "type": "text"},
        ],
    },
}
