"""Phase 4: project, project_member, meeting_project, task.project_id FK

Revision ID: 04e56627dce2
Revises: cf0135a8151d
Create Date: 2026-09-04 16:38:06.350178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e56627dce2'
down_revision = 'cf0135a8151d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_employee_code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='md_project_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='md_task_priority'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_project_owner_employee_code'), ['owner_employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_project_project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_md_project_status'), ['status'], unique=False)

    op.create_table('md_meeting_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tagged_by', sa.String(length=64), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['md_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'project_id', name='uq_meeting_project')
    )
    with op.batch_alter_table('md_meeting_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_project_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_meeting_project_project_id'), ['project_id'], unique=False)

    op.create_table('md_project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['md_project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'employee_code', name='uq_project_member')
    )
    with op.batch_alter_table('md_project_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_project_member_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_project_member_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('md_task', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'md_project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('md_project_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_project_member_project_id'))
        batch_op.drop_index(batch_op.f('ix_md_project_member_employee_code'))

    op.drop_table('md_project_member')
    with op.batch_alter_table('md_meeting_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_project_project_id'))
        batch_op.drop_index(batch_op.f('ix_md_meeting_project_meeting_id'))

    op.drop_table('md_meeting_project')
    with op.batch_alter_table('md_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_project_status'))
        batch_op.drop_index(batch_op.f('ix_md_project_project_code'))
        batch_op.drop_index(batch_op.f('ix_md_project_owner_employee_code'))

    op.drop_table('md_project')
    # ### end Alembic commands ###
