"""Add attendees_emails to Meeting and to_emails to MeetingFollowupEmail

Revision ID: 0a00c644407c
Revises: 7b1fe66f547c
Create Date: 2026-09-07 16:33:31.910026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a00c644407c'
down_revision = '7b1fe66f547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendees_emails', sa.Text(), nullable=True))

    with op.batch_alter_table('md_meeting_followup_email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('to_emails', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_meeting_followup_email', schema=None) as batch_op:
        batch_op.drop_column('to_emails')

    with op.batch_alter_table('md_meeting', schema=None) as batch_op:
        batch_op.drop_column('attendees_emails')

    # ### end Alembic commands ###
