"""Add MeetingFollowupEmail table

Revision ID: 4216a8622826
Revises: 8fd98673f624
Create Date: 2026-09-05 13:18:52.291535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4216a8622826'
down_revision = '8fd98673f624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_meeting_followup_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting_followup_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_followup_email_meeting_id'), ['meeting_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_meeting_followup_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_followup_email_meeting_id'))

    op.drop_table('md_meeting_followup_email')
    # ### end Alembic commands ###
