"""Add MeetingTemplate table

Revision ID: 79486bfe668b
Revises: 4216a8622826
Create Date: 2026-09-05 13:33:53.189972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79486bfe668b'
down_revision = '4216a8622826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_meeting_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('organizer', sa.String(length=200), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('confidentiality_level', sa.Enum('NORMAL', 'RESTRICTED', 'CONFIDENTIAL', name='md_confidentiality_level'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('md_meeting_template')
    # ### end Alembic commands ###
