"""Add EmailIntegration table for Gmail sync

Revision ID: 7b1fe66f547c
Revises: 79486bfe668b
Create Date: 2026-09-07 10:10:39.940349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1fe66f547c'
down_revision = '79486bfe668b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_email_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('google_account_email', sa.String(length=255), nullable=True),
    sa.Column('connected_by', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_email_integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_email_integration_owner_username'), ['owner_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_email_integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_email_integration_owner_username'))

    op.drop_table('md_email_integration')
    # ### end Alembic commands ###
