"""Phase 8: attachment, meeting_transcript, meeting_summary, ai_processing_log

Revision ID: 8fd98673f624
Revises: cd6bbfdfe193
Create Date: 2026-09-04 18:39:40.977150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd98673f624'
down_revision = 'cd6bbfdfe193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_ai_processing_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_length', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_ai_processing_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_ai_processing_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_ai_processing_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_ai_processing_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('md_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('md_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_attachment_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_attachment_entity_type'), ['entity_type'], unique=False)

    op.create_table('md_meeting_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_summary_meeting_id'), ['meeting_id'], unique=True)

    op.create_table('md_meeting_transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting_transcript', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_transcript_meeting_id'), ['meeting_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_meeting_transcript', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_transcript_meeting_id'))

    op.drop_table('md_meeting_transcript')
    with op.batch_alter_table('md_meeting_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_summary_meeting_id'))

    op.drop_table('md_meeting_summary')
    with op.batch_alter_table('md_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_attachment_entity_type'))
        batch_op.drop_index(batch_op.f('ix_md_attachment_entity_id'))

    op.drop_table('md_attachment')
    with op.batch_alter_table('md_ai_processing_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_ai_processing_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_md_ai_processing_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_md_ai_processing_log_created_at'))

    op.drop_table('md_ai_processing_log')
    # ### end Alembic commands ###
