"""Phase 1: app_user and activity_log

Revision ID: a13df0d72df5
Revises: 
Create Date: 2026-09-04 15:43:18.226906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13df0d72df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=64), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_activity_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_activity_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_activity_log_performed_at'), ['performed_at'], unique=False)

    op.create_table('md_app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('MD', 'EA', 'EMPLOYEE', name='md_user_role'), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_app_user_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_app_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_app_user_username'))
        batch_op.drop_index(batch_op.f('ix_md_app_user_employee_code'))

    op.drop_table('md_app_user')
    with op.batch_alter_table('md_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_activity_log_performed_at'))
        batch_op.drop_index(batch_op.f('ix_md_activity_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_md_activity_log_entity_id'))

    op.drop_table('md_activity_log')
    # ### end Alembic commands ###
