"""Phase 5: task_progress_update

Revision ID: c57e9e4080a0
Revises: 04e56627dce2
Create Date: 2026-09-04 17:10:03.201754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57e9e4080a0'
down_revision = '04e56627dce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_task_progress_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.String(length=64), nullable=False),
    sa.Column('update_text', sa.Text(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['md_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_task_progress_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_task_progress_update_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_progress_update_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_progress_update_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_task_progress_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_task_progress_update_task_id'))
        batch_op.drop_index(batch_op.f('ix_md_task_progress_update_employee_code'))
        batch_op.drop_index(batch_op.f('ix_md_task_progress_update_created_at'))

    op.drop_table('md_task_progress_update')
    # ### end Alembic commands ###
