"""Phase 9: notification, reminder

Revision ID: cd6bbfdfe193
Revises: d8264a0df3e7
Create Date: 2026-09-04 17:53:12.981639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6bbfdfe193'
down_revision = 'd8264a0df3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_username', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_notification_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_notification_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_notification_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_notification_recipient_username'), ['recipient_username'], unique=False)

    op.create_table('md_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['md_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_reminder_remind_at'), ['remind_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_reminder_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_reminder_task_id'))
        batch_op.drop_index(batch_op.f('ix_md_reminder_remind_at'))

    op.drop_table('md_reminder')
    with op.batch_alter_table('md_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_notification_recipient_username'))
        batch_op.drop_index(batch_op.f('ix_md_notification_notification_type'))
        batch_op.drop_index(batch_op.f('ix_md_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_md_notification_entity_type'))
        batch_op.drop_index(batch_op.f('ix_md_notification_entity_id'))
        batch_op.drop_index(batch_op.f('ix_md_notification_created_at'))

    op.drop_table('md_notification')
    # ### end Alembic commands ###
