"""Phase 3: meeting, meeting_note, meeting_decision, task, task_assignee

Revision ID: cf0135a8151d
Revises: a13df0d72df5
Create Date: 2026-09-04 16:08:41.638574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0135a8151d'
down_revision = 'a13df0d72df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_calendar_event_id', sa.String(length=200), nullable=True),
    sa.Column('calendar_provider', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('organizer', sa.String(length=200), nullable=True),
    sa.Column('meeting_type', sa.String(length=100), nullable=True),
    sa.Column('attendees_text', sa.Text(), nullable=True),
    sa.Column('confidentiality_level', sa.Enum('NORMAL', 'RESTRICTED', 'CONFIDENTIAL', name='md_confidentiality_level'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD', name='md_meeting_status'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_external_calendar_event_id'), ['external_calendar_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_meeting_start_datetime'), ['start_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_meeting_status'), ['status'], unique=False)

    op.create_table('md_meeting_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_decision_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('md_meeting_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_meeting_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_meeting_note_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('md_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('MEETING_ACTION', 'PROJECT_TASK', 'GENERAL_FOLLOWUP', name='md_task_type'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='md_task_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='md_task_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['md_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_task_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_task_type'), ['task_type'], unique=False)

    op.create_table('md_task_assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('assigned_by', sa.String(length=64), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['md_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'employee_code', name='uq_task_assignee')
    )
    with op.batch_alter_table('md_task_assignee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_task_assignee_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_task_assignee_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_task_assignee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_task_assignee_task_id'))
        batch_op.drop_index(batch_op.f('ix_md_task_assignee_employee_code'))

    op.drop_table('md_task_assignee')
    with op.batch_alter_table('md_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_task_task_type'))
        batch_op.drop_index(batch_op.f('ix_md_task_status'))
        batch_op.drop_index(batch_op.f('ix_md_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_md_task_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_md_task_due_date'))

    op.drop_table('md_task')
    with op.batch_alter_table('md_meeting_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_note_meeting_id'))

    op.drop_table('md_meeting_note')
    with op.batch_alter_table('md_meeting_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_decision_meeting_id'))

    op.drop_table('md_meeting_decision')
    with op.batch_alter_table('md_meeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_meeting_status'))
        batch_op.drop_index(batch_op.f('ix_md_meeting_start_datetime'))
        batch_op.drop_index(batch_op.f('ix_md_meeting_external_calendar_event_id'))

    op.drop_table('md_meeting')
    # ### end Alembic commands ###
