"""Phase 7: calendar_integration, calendar_sync_log

Revision ID: d8264a0df3e7
Revises: c57e9e4080a0
Create Date: 2026-09-04 17:36:55.574995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8264a0df3e7'
down_revision = 'c57e9e4080a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_calendar_integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('google_account_email', sa.String(length=255), nullable=True),
    sa.Column('connected_by', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_calendar_integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_calendar_integration_owner_username'), ['owner_username'], unique=True)

    op.create_table('md_calendar_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('events_fetched', sa.Integer(), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['md_calendar_integration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('md_calendar_sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_md_calendar_sync_log_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_md_calendar_sync_log_synced_at'), ['synced_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('md_calendar_sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_calendar_sync_log_synced_at'))
        batch_op.drop_index(batch_op.f('ix_md_calendar_sync_log_integration_id'))

    op.drop_table('md_calendar_sync_log')
    with op.batch_alter_table('md_calendar_integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_md_calendar_integration_owner_username'))

    op.drop_table('md_calendar_integration')
    # ### end Alembic commands ###
